[package]
name = "fiction"
version = "0.20221114.0"
edition = "2021"

[dependencies]
ammonia = "3.2.1"
async-trait = "0.1.58"
blake3 = { version = "1.3.1", features = ["traits-preview"] }
bstr = { version = "1.0.1", features = ["serde"] }
color-eyre = "0.6.2"
derive_more = "0.99.17"
duct = "0.13.5"
eyre = "0.6.8"
flexbuffers = "2.0.0"
futures = "0.3.24"
heapless = "0.7.16"
hex = "0.4.3"
home = "0.5.4"
http = "0.2.8"
miette = "5.4.1"
once_cell = "1.14.0"
postcard = { version = "1.0.2", features = ["alloc", "use-std"] }
reqwest = { version = "0.11.11", features = ["cookies", "gzip", "deflate", "multipart", "json", "blocking", "rustls-tls", "rustls"] }
rusqlite = { version = "0.28.0", features = ["bundled", "functions", "serde_json", "blob", "time", "url", "vtab", "column_decltype", "series", "window", "load_extension", "backup"] }
rusqlite_migration = "1.0.0"
sapi-lite = { version = "0.1.1", features = ["tokio-tts", "tokio-rt"] }
scraper = "0.13.0"
serde = { version = "1.0.144", features = ["derive", "rc"] }
serde_bytes = "0.11.7"
serde_cbor = "0.11.2"
serde_json = "1.0.85"
serde_with = "2.0.1"
static_assertions = "1.1.0"
tempfile = "3.3.0"
thiserror = "1.0.32"
time = { version = "0.3.14", features = ["serde", "formatting", "parsing"] }
tokio = { version = "1.21.0", features = ["macros", "rt", "fs", "io-std", "io-util", "net", "time", "process"] }
tracing = "0.1.36"
tracing-error = "0.2.0"
tracing-subscriber = { version = "0.3.15", features = [ "std", "env-filter" ] }
which = { version = "4.3.0", features = ["regex"] }
windows = { version = "0.39.0", features = ["Foundation", "Foundation_Collections", "Media_Core", "Media_SpeechSynthesis", "Storage_Streams", "Win32_Media_Speech", "Win32_Foundation", "Win32_System_Com", "Win32_System_Ole", "Win32_Media", "Win32_Media_Multimedia"] }
zip = "0.6.3"

[features]
EDITOR = []
