[package]
name = "fiction"
version = "0.0.0-dev"
edition = "2021"

[dependencies]
async-executor = "1.4.1"
futures-lite = "1.12.0"
thiserror = "1.0.32"
tracing = "0.1.36"
tracing-subscriber = "0.3.15"
bstr = "0.2.17"
serde = { version = "1.0.144", features = ["derive"] }

[dependencies.miette]
version = "5.3.0"
features = [
    "fancy"
]

[dependencies.windows]
version = "0.39.0"
features = [
    "Foundation",
    "Media_Core",
    "Media_SpeechSynthesis",
    "Storage_Streams",
]
