[package]
name = "fiction"
version = "0.0.0-dev"
edition = "2021"

[dependencies]
bstr = "1.0.0"
once_cell = "1.14.0"
reqwest = { version = "0.11.11", features = ["cookies", "gzip", "deflate", "multipart", "json"] }
scraper = "0.13.0"
serde = { version = "1.0.144", features = ["derive"] }
serde_json = "1.0.85"
thiserror = "1.0.32"
tokio = { version = "1.21.0", features = ["macros", "rt"] }
tracing = "0.1.36"
tracing-subscriber = { version = "0.3.15", features = [ "std", "env-filter" ] }
http = "0.2.8"
twox-hash = "1.6.3"

[dependencies.miette]
version = "5.3.0"
features = [
    "fancy"
]

[dependencies.windows]
version = "0.39.0"
features = [
    "Foundation",
    "Media_Core",
    "Media_SpeechSynthesis",
    "Storage_Streams",
]

[dependencies.winsafe]
version = "0.0.11"
features = []
