[package]
name = "fiction"
version = "0.0.0-dev"
edition = "2021"

[dependencies]
ammonia = "3.2.1"
bstr = "1.0.0"
color-eyre = "0.6.2"
erased-serde = "0.3.23"
eyre = "0.6.8"
http = "0.2.8"
miette = { version = "5.3.0", features = ["fancy"] }
once_cell = "1.14.0"
pulldown-cmark = "0.9.2"
reqwest = { version = "0.11.11", features = ["cookies", "gzip", "deflate", "multipart", "json"] }
scraper = "0.13.0"
serde = { version = "1.0.144", features = ["derive", "rc"] }
serde_json = "1.0.85"
static_assertions = "1.1.0"
thiserror = "1.0.32"
tokio = { version = "1.21.0", features = ["macros", "rt", "fs", "io-std", "io-util", "net", "time", "process"] }
tracing = "0.1.36"
tracing-error = "0.2.0"
tracing-subscriber = { version = "0.3.15", features = [ "std", "env-filter" ] }
twox-hash = "1.6.3"
windows = { version = "0.39.0", features = ["Foundation", "Media_Core", "Media_SpeechSynthesis", "Storage_Streams"] }
