[package]
name = "bib"
version = "0.0.0-dev"
edition = "2021"

[dependencies]
smol = "1.2.5"
thiserror = "1.0.32"
tracing = "0.1.36"
tracing-subscriber = "0.3.15"
async-executor = "1.4.1"
futures-lite = "1.12.0"


[dependencies.miette]
version = "5.3.0"
features = [
    "fancy"
]

[dependencies.windows]
version = "0.39.0"
features = [
    "Foundation_Collections",
    "Foundation",
    "Media_Core",
    "Media_SpeechSynthesis",
    "Storage_Streams",
]
