[package]
name = "fiction"
version = "0.0.0-dev"
edition = "2021"

[dependencies]
ambassador = "0.3.5"
ammonia = "3.2.1"
arrayvec = { version = "0.7.2", features = ["serde"] }
blake3 = { version = "1.3.1", features = ["traits-preview"] }
bstr = { version = "1.0.0", features = ["serde"] }
color-eyre = "0.6.2"
derive_more = "0.99.17"
digest = "0.10.5"
duct = "0.13.5"
error-stack = { version = "0.2.1", features = ["spantrace", "eyre", "std", "anyhow"] }
eyre = "0.6.8"
futures = "0.3.24"
heapless = "0.7.16"
hex = "0.4.3"
http = "0.2.8"
leb128 = "0.2.5"
miette = { version = "5.3.0", features = ["fancy"] }
once-cell-regex = "0.2.1"
once_cell = "1.14.0"
postcard = { version = "1.0.2", features = ["alloc", "use-std"] }
regex = "1.6.0"
reqwest = { version = "0.11.11", features = ["cookies", "gzip", "deflate", "multipart", "json"] }
rusqlite = { version = "0.28.0", features = ["bundled", "functions", "serde_json", "blob", "time", "url", "vtab", "column_decltype", "series", "window", "load_extension", "backup"] }
rusqlite_migration = "1.0.0"
sapi-lite = { version = "0.1.1", features = ["tokio-tts", "tokio-rt"] }
scraper = "0.13.0"
serde = { version = "1.0.144", features = ["derive", "rc"] }
serde_json = "1.0.85"
static_assertions = "1.1.0"
tempfile = "3.3.0"
thiserror = "1.0.32"
time = { version = "0.3.14", features = ["serde", "formatting", "parsing"] }
tokio = { version = "1.21.0", features = ["macros", "rt", "fs", "io-std", "io-util", "net", "time", "process"] }
tracing = "0.1.36"
tracing-error = "0.2.0"
tracing-subscriber = { version = "0.3.15", features = [ "std", "env-filter" ] }
twox-hash = "1.6.3"
typenum = "1.15.0"
which = { version = "4.3.0", features = ["regex"] }
windows = { version = "0.39.0", features = ["Foundation", "Foundation_Collections", "Media_Core", "Media_SpeechSynthesis", "Storage_Streams", "Win32_Media_Speech", "Win32_Foundation", "Win32_System_Com", "Win32_System_Ole", "Win32_Media", "Win32_Media_Multimedia"] }

[features]
phony = []
