[package]
name = "fiction"
version = "0.0.0-dev"
edition = "2021"

[dependencies]
async-executor = "1.4.1"
futures-lite = "1.12.0"
thiserror = "1.0.32"
tracing = "0.1.36"
tracing-subscriber = "0.3.15"
bstr = "1.0.0"
serde = { version = "1.0.144", features = ["derive"] }
once_cell = "1.14.0"
html5ever = "0.26.0"
markup5ever_rcdom = "0.2.0"
scraper = "0.13.0"
hyper = "0.14.20"
tokio = { version = "1.21.0", features = ["macros", "rt"] }
reqwest = "0.11.11"

[dependencies.miette]
version = "5.3.0"
features = [
    "fancy"
]

[dependencies.windows]
version = "0.39.0"
features = [
    "Foundation",
    "Media_Core",
    "Media_SpeechSynthesis",
    "Storage_Streams",
]
