enum_discrim_align_threshold = 64
force_explicit_abi = false
format_code_in_doc_comments = true
format_macro_bodies = true
format_macro_matchers = true
format_strings = true
group_imports = "StdExternalCrate"
imports_granularity = "Item"
match_arm_blocks = false
match_block_trailing_comma = true
newline_style = "Unix"
overflow_delimited_expr = true
struct_field_align_threshold = 64
unstable_features = true
use_field_init_shorthand = true
wrap_comments = true
