{
  "name": "action",
  "on": [
    "push",
    "pull_request",
    "workflow_dispatch"
  ],
  "jobs": {
    "deno": {
      "runs-on": "ubuntu-latest",
      "permissions": {
        "id-token": "write",
        "contents": "read"
      },
      "steps": [
        {
          "uses": "actions/checkout@v3"
        },
        {
          "name": "deno tooling",
          "uses": "denoland/setup-deno@v1"
        },
        {
          "name": "deno build",
          "run": "cd deno && deno check --lock lock.json main.ts"
        },
        {
          "name": "deno formatting",
          "run": "cd deno && deno fmt --check",
          "continue-on-error": true
        },
        {
          "name": "deno lint",
          "run": "cd deno && deno lint",
          "continue-on-error": true
        },
        {
          "name": "deno deploy",
          "uses": "denoland/deployctl@v1",
          "with": {
            "project": "fic",
            "root": "deno",
            "entrypoint": "main.ts",
            "import-map": "import_map.json",
          }
        }
      ]
    },
    "rust": {
      "runs-on": "ubuntu-latest",
      "steps": [
        {
          "uses": "actions/checkout@v3"
        },
        {
          "name": "rust build",
          "run": "cargo build --locked"
        },
        {
          "name": "rust formatting",
          "run": "cargo fmt --check",
          "continue-on-error": true
        },
        {
          "name": "rust lint",
          "run": "cargo clippy",
          "continue-on-error": true
        }
      ]
    }
  }
}
